### ISSUE TITLE
PHP Catchable fatal error

### ISSUE THREAD

**Issue by PioBeat** [cturbelin/rserve-php#13]
This error occurs if calling method ```as.Character()``` from the class ```Rserve_REXP_Factor```.

Problem is a duplicate ```$``` in front of the return variable.

Full error message:
Catchable fatal error:  Object of class Rserve_REXP_String could not be converted to string in PATH_TO_FILE/REXP/Factor.php on line 54

**Comment by cturbelin** [comment]
Thank you, it has been fixed in c3956457a549bdc7c533e312169d90c3c5f19fda (branch 2.0)
